### ISSUE TITLE
cant create claim in fact check form

### ISSUE THREAD

**Issue by shreeharsha-factly** [factly/dega#528] opened 2022-05-10 11:31 UTC

**Comment by surajmn1** [comment] 2022-05-12 12:57
Cant reproduce the issue

**Comment by vsumit89** [comment] 2022-05-17 13:03
So the issue was that user was trying to hit okay button which was part of the modal and not the create claim form because of which the claim was not being created, but the modal was closing so it was appearing as if the request has been sent. To solve this issue we removed the okay and cancel button at the bottom of the modal.

**Closed as completed** 2022-05-17 13:15 UTC
Labels: studio
